version: "3.2"

services:
    ## en-marche.fr
    ###############
    app:
        networks:
            default:
                aliases:
                    - test.enmarche.code
                    - enmarche.code
        build: docker/dev
        depends_on:
            - db
            - redis
            - rabbitmq
        volumes:
            - .:/app

    db:
        image: mdillon/postgis:9.6
        environment:
            POSTGRES_DB: enmarche
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root

    redis:
        image: redis:3.2

    ## testing
    ####################
    selenium:
        image: selenium/standalone-firefox-debug:2.53.1
        shm_size: 2g

    ## common
    ####################
    rabbitmq:
        image: rabbitmq:3-management
